[path]
root = "/Users/burcel/projects/traffic-signs"
model_folder = "models"
log_folder = "log"
data_folder = "data"

[training]
validation_split_percentage = 20
batch_size = 32
epoch = 100
early_stop_epoch = 10

[adam]
learning_rate = 0.00005
beta1 = 0.9
beta2 = 0.999

[gtsrb]
training_folder = "GTSRB_Final_Training_Images/Final_Training/Images"
test_folder = "GTSRB_Final_Test_Images/Final_Test/Images"
